### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.error#2]
Seems to be because of the update in `persistent`.

See https://travis-ci.org/zopefoundation/zope.app.dependable/builds/443424814

**Comment by jamadden** [comment]
I've confirmed this is fixed with https://github.com/zopefoundation/persistent/pull/98

**Comment by icemac** [comment]
TravisCI is now green: https://travis-ci.org/zopefoundation/zope.app.error/builds/443424824
